In [2]:
# read in the data from the excel file  "QC Anomaly Training Data.xlsx" and show the first 10 rows
# you have to  get data from the sheet called  'STD-BLK-SPK Assessment' and make a data frame from the sheet 'REP-DUP assessment'ArithmeticError
import pandas as pd
file_path = "data/QC Anomaly Training Data.xlsx"

# read the data from the specified sheet into a DataFrame
df_1 = pd.read_excel(file_path, sheet_name='STD-BLK-SPK Assessment')
df_2 = pd.read_excel(file_path, sheet_name='REP-DUP assessment')
# show the first 10 rows of the DataFrame
df_1.head(10)

,ANALYTICAL_TYPE,STD_LOT_CODE,STD_CODE,JOB_CODE,NUMERIC_FINAL_VALUE,ANALYSED_DATE,SCHEME_CODE,ANALYTE_CODE,STANDARD_STATUS,PRECISION_STATUS,...,INTERNAL_MAX_WARNING_INCLUSIVE,LIM_REP_VALUE,STAT_DL_VALUE,LIM_REP_DUP_VALUE,STAT_DL_DUP_VALUE,INTERNAL_TARGET_VALUE,PARENT_NUMERIC_FINAL_VALUE,UNIT_CODE,SPECIFICATION_CODE,INSTRUMENT_ID
0,Standard,OREAS_905,OREAS_905,TSV_LB0016663011,35.927171,2021-11-22 16:37:52,GE_IMS40Q12,PB,UpperFailure,NaN,...,Y,10,1.25,15.0,1.25,30.40,NaN,MG_KG,OREAS_905,NaN
1,Standard,OREAS_905,OREAS_905,TSV_LB0016663011,55.639610,2021-11-22 16:37:52,GE_IMS40Q12,PB,UpperFailure,NaN,...,Y,10,1.25,15.0,1.25,30.40,NaN,MG_KG,OREAS_905,NaN
2,Replicate,Sample,Sample,TSV_LB0016663011,1492.268392,2021-11-22 16:37:52,GE_IMS40Q12,PB,NaN,Warning,...,NaN,10,1.25,15.0,1.25,NaN,1385.198107,MG_KG,NaN,NaN
3,Replicate,Sample,Sample,TSV_LB0016663011,18.525452,2021-11-22 16:37:33,GE_IMS40Q12,NI,NaN,Pass,...,NaN,10,5.00,15.0,5.00,NaN,16.334782,MG_KG,NaN,NaN
4,Standard,OREAS_905,OREAS_905,TSV_LB0016663011,11.742601,2021-11-22 16:37:33,GE_IMS40Q12,NI,UpperWarning,NaN,...,Y,10,5.00,15.0,5.00,9.54,NaN,MG_KG,OREAS_905,NaN
5,Standard,OREAS_905,OREAS_905,TSV_LB0016663011,12.236060,2021-11-22 16:37:33,GE_IMS40Q12,NI,UpperFailure,NaN,...,Y,10,5.00,15.0,5.00,9.54,NaN,MG_KG,OREAS_905,NaN
6,Blank,TSV_BLANK,TSV_BLANK,TSV_LB0016663011,-0.139828,2021-11-22 16:36:25,GE_IMS40Q12,NI,Pass,NaN,...,Y,10,5.00,15.0,5.00,0.00,NaN,MG_KG,TSV_BLANK,NaN
7,Standard,OREAS_905,OREAS_905,TSV_LB0016663011,1501.882410,2021-11-22 16:35:49,GE_IMS40Q12,CU,Pass,NaN,...,Y,10,5.00,15.0,5.00,1533.00,NaN,MG_KG,OREAS_905,NaN
8,Standard,OREAS_905,OREAS_905,TSV_LB0016663011,1550.868306,2021-11-22 16:35:49,GE_IMS40Q12,CU,Pass,NaN,...,Y,10,5.00,15.0,5.00,1533.00,NaN,MG_KG,OREAS_905,NaN
9,Replicate,Sample,Sample,TSV_LB0016663011,14.901179,2021-11-22 16:35:49,GE_IMS40Q12,AG,NaN,Pass,...,NaN,10,0.05,15.0,0.05,NaN,14.647905,MG_KG,NaN,NaN

In [3]:
df_2.head(10)

,ANALYTICAL_TYPE,SCHEME_CODE,ANALYTE_CODE,UNIT_CODE,ANALYSED_DATE,NUMERIC_FINAL_VALUE,PARENT_NUMERIC_FINAL_VALUE,PRECISION_STATUS,LIM_REP_VALUE,STAT_DL_VALUE,...,AbsDiff,Avg,Abs%Diff,Fail Limit,Warn Limit,Status,,.1,.2,
0,Replicate,GE_IMS40Q12,CU,MG_KG,2021-07-20 14:17:36.000,-1780.355970,30.808299,IgnoreFailure,10,5.0,...,1811.164269,-874.773835,207.043718,10.571576,6.705595,Failure,NaN,NaN,NaN,NaN
1,Replicate,GE_ICP40Q12,CR,MG_KG,2021-09-02 15:51:13.000,-110.072261,-116.916780,Pass,15,2.5,...,6.844518,-113.494521,6.030704,17.202750,10.911776,Pass,NaN,NaN,NaN,NaN
2,Replicate,GE_ICP40Q12,CR,MG_KG,2021-04-28 03:04:33.000,-81.145279,-82.605612,Pass,15,2.5,...,1.460333,-81.875446,1.783603,18.053418,11.451359,Pass,NaN,NaN,NaN,NaN
3,Replicate,GE_ICP40Q12,BI,MG_KG,2021-03-22 06:43:40.000,-65.592040,-65.592040,Pass,10,12.5,...,0.000000,-65.592040,0.000000,29.057191,18.431098,Pass,NaN,NaN,NaN,NaN
4,Replicate,GE_ICP40Q12,BI,MG_KG,2020-12-14 07:39:45.540,-70.158416,-58.553398,Pass,10,12.5,...,11.605018,-64.355907,18.032560,29.423236,18.663283,Pass,NaN,NaN,NaN,NaN
5,Replicate,GE_ICP40Q12,BI,MG_KG,2021-06-22 12:45:29.000,-64.631708,-57.670115,Pass,10,12.5,...,6.961593,-61.150912,11.384283,30.441232,19.309002,Pass,NaN,NaN,NaN,NaN
6,Replicate,GE_ICP40Q12,BI,MG_KG,2020-11-30 11:33:54.000,-56.344086,-56.507937,Pass,10,12.5,...,0.163850,-56.426011,0.290381,32.152904,20.394722,Pass,NaN,NaN,NaN,NaN
7,Replicate,GE_ICP40Q12,BI,MG_KG,2021-04-12 07:43:54.450,-45.628875,-48.751279,Pass,10,12.5,...,3.122404,-47.190077,6.616653,36.488620,23.144885,Pass,NaN,NaN,NaN,NaN
8,Replicate,GE_ICP40Q12,BI,MG_KG,2021-04-12 07:40:31.504,-47.693999,-44.271854,Pass,10,12.5,...,3.422145,-45.982926,7.442208,37.184003,23.585970,Pass,NaN,NaN,NaN,NaN
9,Replicate,GE_ICP40Q12,BI,MG_KG,2021-04-12 07:40:27.793,-41.376246,-49.121961,Pass,10,12.5,...,7.745715,-45.249103,17.117942,37.624857,23.865605,Pass,NaN,NaN,NaN,NaN

In [6]:
df_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 99999 entries, 0 to 99998
Data columns (total 27 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ANALYTICAL_TYPE                 99999 non-null  str
 1   STD_LOT_CODE                    99999 non-null  str
 2   STD_CODE                        99999 non-null  str
 3   JOB_CODE                        99999 non-null  str
 4   NUMERIC_FINAL_VALUE             99999 non-null  float64
 5   ANALYSED_DATE                   99999 non-null  datetime64[us]
 6   SCHEME_CODE                     99999 non-null  str
 7   ANALYTE_CODE                    98871 non-null  str
 8   STANDARD_STATUS                 54675 non-null  str
 9   PRECISION_STATUS                45315 non-null  str
 10  INTERNAL_MIN_VALUE              54447 non-null  float64
 11  INTERNAL_MAX_VALUE              54447 non-null  float64
 12  INTERNAL_MIN_INCLUSIVE          54677 non-null  str
 13  INTERNAL_MAX_INCLUSIVE          54677 non-null  str
 14  INTERNAL_MAX_WARNING_VALUE      36450 non-null  float64
 15  INTERNAL_MIN_WARNING_VALUE      36450 non-null  float64
 16  INTERNAL_MIN_WARNING_INCLUSIVE  54677 non-null  str
 17  INTERNAL_MAX_WARNING_INCLUSIVE  54677 non-null  str
 18  LIM_REP_VALUE                   99999 non-null  int64
 19  STAT_DL_VALUE                   99999 non-null  float64
 20  LIM_REP_DUP_VALUE               99999 non-null  float64
 21  STAT_DL_DUP_VALUE               99999 non-null  float64
 22  INTERNAL_TARGET_VALUE           54445 non-null  float64
 23  PARENT_NUMERIC_FINAL_VALUE      45315 non-null  float64
 24  UNIT_CODE                       99999 non-null  str
 25  SPECIFICATION_CODE              54683 non-null  str
 26  INSTRUMENT_ID                   1 non-null      str
dtypes: datetime64[us](1), float64(10), int64(1), str(15)
memory usage: 27.4 MB

In [ ]:
df['STANDARD_STATUS'].unique()

df['ANALYTICAL_TYPE'].unique()

<ArrowStringArray>
['Standard', 'Blank']
Length: 2, dtype: str

In [9]:
df_1['ANALYTICAL_TYPE'].unique()

<ArrowStringArray>
['Standard', 'Replicate', 'Blank', 'Duplicate']
Length: 4, dtype: str

In [10]:
df_2['ANALYTICAL_TYPE'].unique()

<ArrowStringArray>
['Replicate', 'Duplicate']
Length: 2, dtype: str

In [ ]:
df[df['ANALYTICAL_TYPE']== 'Blank'].head(10)